# Generated by Django 4.2.5 on 2023-09-30 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0004_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Units',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Unit_Name', models.CharField(max_length=5)),
                ('Unit_Code', models.CharField(max_length=15)),
            ],
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
