# Generated by Django 4.2.5 on 2023-09-30 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0005_units_delete_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='units',
            name='Unit_Name',
            field=models.CharField(max_length=50),
        ),
    ]
