# Generated by Django 4.2.5 on 2023-09-30 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0006_alter_units_unit_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nominals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_Name', models.CharField(max_length=50)),
                ('Student_ID', models.CharField(max_length=15)),
                ('Course', models.CharField(max_length=15)),
                ('Semester', models.IntegerField(max_length=1)),
            ],
        ),
    ]
