# Generated by Django 4.2.5 on 2023-09-30 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0007_nominals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nominals',
            name='Semester',
            field=models.IntegerField(),
        ),
    ]
