# Generated by Django 4.2.5 on 2023-09-30 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0008_alter_nominals_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nominals',
            name='Course',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='nominals',
            name='Student_ID',
            field=models.CharField(max_length=20),
        ),
    ]
