# Generated by Django 4.2.5 on 2023-09-30 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0009_alter_nominals_course_alter_nominals_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nominals',
            name='Student_ID',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
