# Generated by Django 4.2.5 on 2023-09-30 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0012_alter_nominals_student_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nominals',
            name='Student_ID',
        ),
    ]
