# Generated by Django 4.2.5 on 2023-09-30 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0013_remove_nominals_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='nominals',
            name='Student_ID',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
