# Generated by Django 4.2.5 on 2023-09-30 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0014_nominals_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nominals',
            name='Course',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='nominals',
            name='Student_ID',
            field=models.CharField(max_length=55),
        ),
    ]
